const cartActions = {
    ADD_TO_CART: "ADD_TO_CART",
    UPDATE_TOTAL: "UPDATE_TOTAL",
    REMOVE_PRODUCTS: "REMOVE_PRODUCTS",
    UPDATE_PRODUCTS_IN_CART: "UPDATE_PRODUCTS_IN_CART"
};

export { cartActions };
